# Generated by Django 3.1.1 on 2020-09-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_usersplans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersplans',
            old_name='plan',
            new_name='plans',
        ),
    ]
